### ISSUE TITLE
Transiants not stored in database if object caches is enabled.

### ISSUE THREAD

**Issue by spacedmonkey** [felixarntz/flush-transients#1]
If object caches is enabled, transiants are not stored in database the site meta / options tables. Query like this will not work.

https://github.com/felixarntz/flush-transients/blob/d35ace7b00de771c4301293ec2ab740a4e08a484/db.php#L33-L40
https://github.com/felixarntz/flush-transients/blob/d35ace7b00de771c4301293ec2ab740a4e08a484/db.php#L84-L91

**Comment by felixarntz** [comment]
See https://github.com/felixarntz/flush-transients/blob/main/db.php#L16, these functions aren't used when using a persistent object cache. So I believe the plugin already accounts for that.

**Comment by spacedmonkey** [comment]
@felixarntz with a small tweak, it could be used with persistent object caching

**Comment by felixarntz** [comment]
@spacedmonkey I think that's already the case, see https://github.com/felixarntz/flush-transients/blob/main/ui.php#L33: If a persistent object cache is used, it flushes the relevant cache group.

Regarding the queries: I am not aware of any reliable way to detect the number of cache keys in a group. Let me know if you have any idea for that.
